### ISSUE TITLE
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location.

### ISSUE THREAD

**Issue by Etienne66** [alpErenSari/spatioTemporalTransformer#2]
The full errors is: 
```python
Traceback (most recent call last):
      File "main_spatio.py", line 164, in <module>
        main()
      File "main_spatio.py", line 104, in main
        train(training_data_loader, optimizer, model, criterion, epoch)
      File "main_spatio.py", line 134, in train
        loss = criterion(model(input), target)
      File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "F:\workspaces\spatioTemporalTransformer\models.py", line 365, in forward
        out6 = self.flow_warp_5d(x, out5)
      File "F:\workspaces\spatioTemporalTransformer\models.py", line 347, in flow_warp_5d
        grid[:, :, 0, :, :] = 2 * grid[:, :, 0, :, :] / (w - 1) - 1
    RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
```

I setup an environment with pytorch 1.3.0 by doing the following
`conda install pytorch==1.3.0 torchvision==0.4.1 cudatoolkit=10.1 -c pytorch`
`conda install h5py`

I was trying to run the training using the `F:\workspaces\data\DeepVideoDeblurring_Dataset`.

I ran `python main_spatio.py --cuda` with no other options letting it take the defaults.

I tried again with just `python main_spatio.py` but it still gave the exact same error.

**Comment by Etienne66** [comment]
I reverted `main_spatio.py` and `models.py` to the original files for history b7f787b that you checked in and it seems to be running.
